# This is a basic workflow to help you get started with Actions

name: Github Actions demo  
on:
  workflow_dispatch:
    inputs: 
      environment: 
        required: true
        description: Which environment to deploy to
        type: environment
  pull_request:
    branches: main
  push:
    branches: main
    paths-ignore: .github/**
  schedule:
    - cron: 15 6 * * 0
       
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered by event: ${{github.event_name}}"
          echo "The name of your branch is ${{ github.ref }} and your repository is ."
      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  test:
    environment: Test
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: "echo \"Testing...\""
  
  load-test:
    environment: Load-Test
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: "echo \"Testing...\""

      - run: sleep 15

  production:
    environment: Production
    needs: [test, load-test]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: "echo \"Deploying 1\""
      - run: sleep 5

      - run: "echo \"Deploying 2\""
      - run: sleep 5
      

  
